<?php
	$data	=	$this->getLoadedProductCollection();
	
    $_helper = $this->helper('catalog/output');	
    $em0039 = new EM_Em0039settings_Em0039settings();
    $bg = $em0039->get_mostpopular_bgcolor();
    $w = $em0039->get_mostpopular_width();
    $h = $em0039->get_mostpopular_height();

?>
<?php if(count($data) == 0): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
	<div class="widget-title">
        <h2><?php echo $this->__('Most Popular') ?></h2>
    </div>    
    <?php $_collectionSize = $data->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($data as $_product): ?>
	<?php if(($this->getData('special') == 3 or $this->getData('special') == 4 ) && $data->isEnabledFlat() ) : ?>
		<?php $_product	=	 Mage::getModel('catalog/product')->load($_product->getId()) ?>
	<?php endif ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="product-content">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w, $h); ?>" width="<?php echo $w; ?>" height="<?php echo $h; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                    <div class="name-price">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <?php echo $this->getPriceHtml($_product, true) ?></p>
                    </div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        
</div>
    <?php endif; ?>
	



